### ISSUE TITLE
how to do the step 4, Convert videos to frames, resize them etc

### ISSUE THREAD

**Issue by fucusy** [hbilen/dynamic-image-nets#1]
Convert videos to frames, resize them to 256x256 and store them in such a directory structure

**Comment by hbilen** [comment]
If you have ffmpeg installed, you can utils/use extract_frames.sh to convert videos into frames. Then you can just write a simple script (in matlab or bash) or convert frames into the required size. I hope this helps.

**Comment by fucusy** [comment]
thank you, I get this done by ffmpeg.
