### ISSUE TITLE
Visualizing dynamic image

### ISSUE THREAD

**Issue by entalent** [hbilen/dynamic-image-nets#10]
Hello,
I wanted to re-implement the function `compute_approximate_dynamic_images` with python and compare the results. But I can't find the function `visualize_approximate_dynamic_images` in the matlab code...
I tried to perform L2 normalization on the output of `compute_approximate_dynamic_images`, and multiply the values by 255 to get an image. Is this the correct way of visualizing dynamic image?

**Comment by zhengying1013** [comment]
@entalent I have written a script to visualize the dynamic image. Hope this can help you.

`function show_dynamic_images()

% the path of video frames you want to compute the dynamic image
image_list = dir('v_BlowDryHair_g01_c01/*.jpg');

len = length(image_list);
imagesA = cell(1, len) ;
for i = 1 : len
    path = fullfile('v_BlowDryHair_g01_c01', image_list(i).name);
    imagesA{i} = imread(path) ;
end
images = cat(4, imagesA{:}) ;

N = size(images, 4) ;
di = vl_nnarpooltemporal(single(images), ones(1, N)) ;
ymax = 255;

xmax = max(max(max(di)));
xmin = min(min(min(di)));
D = round(ymax * (di - xmin) / (xmax - xmin));

D = uint8(D);
imshow(D);`

**Comment by zhengying1013** [comment]
@entalent I have written a script to visualize the dynamic image. Hope this can help you.

```
function show_dynamic_images()

% the path of video frames you want to compute the dynamic image
image_list = dir('v_BlowDryHair_g01_c01/*.jpg');

len = length(image_list);
imagesA = cell(1, len) ;
for i = 1 : len
path = fullfile('v_BlowDryHair_g01_c01', image_list(i).name);
imagesA{i} = imread(path) ;
end
images = cat(4, imagesA{:}) ;

N = size(images, 4) ;
di = vl_nnarpooltemporal(single(images), ones(1, N)) ;
ymax = 255;

xmax = max(max(max(di)));
xmin = min(min(min(di)));
D = round(ymax * (di - xmin) / (xmax - xmin));

D = uint8(D);
imshow(D);
```

**Comment by zhengying1013** [comment]
@entalent I have written a script to visualize the dynamic image. Hope this can help you.

```
function show_dynamic_images()

% the path of video frames you want to compute the dynamic image
image_list = dir('v_BlowDryHair_g01_c01/*.jpg');

len = length(image_list);
imagesA = cell(1, len) ;
for i = 1 : len
    path = fullfile('v_BlowDryHair_g01_c01', image_list(i).name);
    imagesA{i} = imread(path) ;
end
images = cat(4, imagesA{:}) ;

N = size(images, 4) ;
di = vl_nnarpooltemporal(single(images), ones(1, N)) ;
ymax = 255;

xmax = max(max(max(di)));
xmin = min(min(min(di)));
D = round(ymax * (di - xmin) / (xmax - xmin));

D = uint8(D);
imshow(D);
```
