### ISSUE TITLE
how to get the single class accuracy

### ISSUE THREAD

**Issue by gaoyuanhong** [hbilen/dynamic-image-nets#11]
from the paper  we can see that the model can only give the average of all the classes and evaluate the whole model  , so how  I can get the single class such as  Biking Class accuracy  ?     thanks for your help !

**Comment by Blssel** [comment]
I have the same question with you. And I am not sure what is the difference between the train and evaluate code here ??

**Comment by Blssel** [comment]
Have you solved the problem？

**Comment by hbilen** [comment]
I have pushed some changes. Now if you follow README evaluation, you should be able to see per class accuracy.
