### ISSUE TITLE
how to choose N?

### ISSUE THREAD

**Issue by KeyKy** [hbilen/dynamic-image-nets#12]
```
function di = compute_approximate_dynamic_images(images)
% Computes approximate dynamic images for a given array of images
% IMAGES must be a tensor of H x W x D x N dimensionality or
% cell of image names
```

I want to use the approximate_dynamic_images. I do not know how to choose N for a video.

**Comment by hbilen** [comment]
We choose N=10 in the paper because it was giving the best accuracy. You may want to try different N values for different datasets or different tasks.
