### ISSUE TITLE
I did not find any code about SI+DI+OF+DOF

### ISSUE THREAD

**Issue by KeyKy** [hbilen/dynamic-image-nets#13]
How did you extract optical flow and DOF

**Comment by hbilen** [comment]
That will be available soon

**Comment by sudonto** [comment]
It is now Nov 2018, will you make it available?

**Comment by hbilen** [comment]
There is already code to train for SI, DI, OF and DOF. We don't train them jointly. At test time, you can just take their scores and average them,
