### ISSUE TITLE
what is SI?

### ISSUE THREAD

**Issue by lvhuafu** [hbilen/dynamic-image-nets#16]
I don't understand the SI(RGB image)
what the different between the DI: dynamic RBG image and SI: RGB image?

**Comment by dracarys983** [comment]
SI stands for **S**ingle **I**mage and DI stands for **D**ynamic **I**mage.

DI is a rank-pooled (operator definition in the [paper](http://www.egavves.com/data/cvpr2016bilen.pdf)) RGB image. Simply put, DI is a RGB image pooled over a set of RGB images, while SI is a single RGB image.

Hope this helps!
