### ISSUE TITLE
Predicting Activity in Video

### ISSUE THREAD

**Issue by sudonto** [hbilen/dynamic-image-nets#19]
Hi, thanks for the code.
Let say, I have one video from UCF101, then I extract the optical flow images from that video. Can I use trained model (`Deploy\resnext50-of-arpool-split1.mat`) and run `cnn_dicnn_of()` to predict predifined activity within this video? Thank you

**Comment by hbilen** [comment]
Yes that should work. If you set opts.epochFactor to zero, it should only evaluate the model.

**Comment by sudonto** [comment]
Nice, will try it soon 👍🏽
