### ISSUE TITLE
how can i see the dynamic image result?

### ISSUE THREAD

**Issue by fucusy** [hbilen/dynamic-image-nets#2]
how can i see the dynamic image result? after run the step 5

**Comment by BrightFeather** [comment]
Did you get the answer?

**Comment by fucusy** [comment]
@BrightFeather  yes, I digged into the matlab code and found the dynamic image. you can see it from my fork branch change log. 
[git-branch-from-my-fork](https://github.com/fucusy/dynamic-image-nets/commit/bdfb8ba9310f9b492650f7dfee2e297e97f2c019)

**Comment by hbilen** [comment]
You can just feed your images to vl_nnarpooltemporal layer and visualize the output.
