### ISSUE TITLE
at step 4, can you share some sample file in data/UCF101/ucfTrainTestlist/

### ISSUE THREAD

**Issue by fucusy** [hbilen/dynamic-image-nets#3]
please show some sample file list in README.md like below

data/UCF101/ucfTrainTestlist/
├── classIndFixed.txt
├── classInd.txt
├── testlist01.txt
├── testlist02.txt
├── testlist03.txt
├── trainlist01.txt
├── trainlist02.txt
└── trainlist03.txt

**Comment by fucusy** [comment]
you can download the txt files at http://crcv.ucf.edu/data/UCF101.php,  there is a text link to http://crcv.ucf.edu/data/UCF101/UCF101TrainTestSplits-RecognitionTask.zip

**Comment by fucusy** [comment]
closed

**Comment by hbilen** [comment]
Thanks @fucusy
