### ISSUE TITLE
dynamci-image show

### ISSUE THREAD

**Issue by fenling** [hbilen/dynamic-image-nets#5]
i want see the dynamic image ,but in the code" vl_nnarpooltemporal layer"get the image is not same with the paper's image.the left image is from paper, the right image is from matlab code.can you help me?
![image](https://cloud.githubusercontent.com/assets/21993862/18235800/d546a4c4-7351-11e6-9092-bb084b8f59a1.png)

**Comment by jxlgdxyan** [comment]
would you mind telling me how to debug the code?  my teacher gave me this paper,but i don't understand at all.   thank you!  my email is 2514931411@qq.com

**Comment by BitFloyd** [comment]
Hey guys, you just need to normalize the image to lie between 0-255 and then do uint8(img) to see the image like in the paper.

**Comment by gaoyuanhong** [comment]
normalize ？     I  didn't get it  ,  could you explain clearly   ?   i have tried histogram equlization, localhistogram ,but it didn't  work

**Comment by BitFloyd** [comment]
@gaoyuanhong, Scale the pixels to lie between 0-255 and make them a uint8 array to view the images.
