### ISSUE TITLE
MDI modility accuracy

### ISSUE THREAD

**Issue by actionderkokon** [hbilen/dynamic-image-nets#7]
hello，i want to know how the accuracy is computed when the input modility is MDI? For SDI, a dynamic have one recognition result while MDI have more than one, in the paper, it seems not to be introduced how      
the MDI accuracy is made.  Thanks for your reply.

**Comment by hbilen** [comment]
Hi,
MDI produces only one score per video as in SDI, as we max pool features after the last convolutional layer. Thus the code already calculates the accuracy without requiring any modification.
