### ISSUE TITLE
obtaining dynamic images.

### ISSUE THREAD

**Issue by actionderkokon** [hbilen/dynamic-image-nets#8]
hey, recently i am reading your paper about dynamic image net, and one question i do not know how to achieve it:
 it seems that the dynamic images are obtained offline, and i do not how to obtain this.

**Comment by hbilen** [comment]
The code automatically compute dynamic images in the forward pass. You do not need to compute them offline.

**Comment by actionderkokon** [comment]
thank u for your reply，and i want to obtain the dynamic images to look at the dataset structure，can u tell me which code can compute this？

**Comment by hbilen** [comment]
Please have a look at readme file
